# ARC Configuration File
# Icons are stored in: /home/admin/Icons/

screen:
  width: 480
  height: 320
  fps: 30

tab:
  width: 100
  height: 40
  margin: 5

accent_color: [204, 99, 36]

colors:
  background: [20, 20, 20]
  background_light: [250, 250, 250]
  tab_bg: [50, 50, 50]
  tab_active: [100, 100, 100]
  button: [220, 220, 220]
  button_hover: [100, 160, 210]
  text_light: [5, 5, 5]
  text: [220, 220, 220]
  warning_bg: [200, 50, 50]
  warning_text: [255, 255, 255]
  indicator: [180, 180, 180]
  indicator_active: [255, 255, 255]
  input_bg: [255, 255, 255]
  input_border: [100, 100, 100]
  input_text: [0, 0, 0]
  input_placeholder: [150, 150, 150]
  cell_bg: [220, 220, 220]
  cell_active: [240, 240, 240]
  accent: [204, 99, 36]
  slider_bg: [80, 80, 80]
  slider_fill: [50, 150, 250]
  slider_knob: [200, 200, 200]
  slider_active_knob: [255, 255, 255]

# Icon paths - Using ABSOLUTE paths to /home/admin/Icons/
icons:
  wifi_locked: /home/admin/Icons/wifi_locked.png
  wifi_unlocked: /home/admin/Icons/wifi_unlocked.png

# Built-in applications - Direct launch with venv Python
builtin_apps:
  - name: Terminal
    icon: /home/admin/Icons/terminal.png
    exec: "kitty --directory=~"

  - name: AI Chatbot
    icon: /home/admin/Icons/AI.png
    exec: "/home/admin/ARC/venv/bin/python /home/admin/ARC/arc/apps/chatbot/main.py"

  - name: Calendar
    icon: /home/admin/Icons/calendar.png
    exec: "/home/admin/ARC/venv/bin/python /home/admin/ARC/arc/apps/calendar/main.py"

  - name: RF tools
    icon: /home/admin/Icons/rf.png
    exec: "/home/admin/ARC/venv/bin/python /home/admin/ARC/arc/apps/rf_tools/main.py"

  - name: IR tools
    icon: /home/admin/Icons/ir.png
    exec: "/home/admin/ARC/venv/bin/python /home/admin/ARC/arc/apps/ir_tools/main.py"

  - name: NFC tools
    icon: /home/admin/Icons/nfc.png
    exec: "/home/admin/ARC/venv/bin/python /home/admin/ARC/arc/apps/nfc_tools/main.py"

  - name: WiFi tools
    icon: /home/admin/Icons/wifi_tools.png
    exec: "/home/admin/ARC/venv/bin/python /home/admin/ARC/arc/apps/wifi_tools/main.py"

  - name: Bluetooth tools
    icon: /home/admin/Icons/bluetooth_tools.png
    exec: "/home/admin/ARC/venv/bin/python /home/admin/ARC/arc/apps/bluetooth_tools/main.py"

  - name: Files
    icon: /home/admin/Icons/files.png
    exec: "pcmanfm"

  - name: Text editor
    icon: /home/admin/Icons/editor.png
    exec: "/home/admin/ARC/venv/bin/python /home/admin/ARC/arc/apps/notes/main.py"

  - name: Music
    icon: /home/admin/Icons/music.png
    exec: "/home/admin/ARC/venv/bin/python /home/admin/ARC/arc/apps/music_player/main.py"

  - name: Games
    icon: /home/admin/Icons/games.png
    exec: "/home/admin/ARC/venv/bin/python /home/admin/ARC/arc/apps/games/main.py"

  - name: ARC connect
    icon: /home/admin/Icons/arc_connect.png
    exec: "/home/admin/ARC/venv/bin/python /home/admin/ARC/arc/apps/connect/ip.py"

# Directory paths
apps_dir: ./apps
packages_dir: ./packages

# Grid layout
grid:
  cols: 4
  rows: 2
  margin: 10
  padding: 30
  x_offset: 4
  y_offset: 0

# Cell dimensions
cell:
  width: 90
  height: 90

# Top bar configuration - Using ABSOLUTE icon paths
topbar:
  height: 30
  bg: [20, 20, 20]
  fg: [200, 200, 200]
  notification_dot: [245, 88, 88]
  icons: []
  icon_battery: /home/admin/Icons/topbar/battery.png
  icon_mobile: /home/admin/Icons/topbar/cellular.png
  wifi_icons:
    - /home/admin/Icons/topbar/wifi_0.png
    - /home/admin/Icons/topbar/wifi_1.png
    - /home/admin/Icons/topbar/wifi_2.png
    - /home/admin/Icons/topbar/wifi_3.png
    - /home/admin/Icons/topbar/wifi_4.png
  icon_bt_on: /home/admin/Icons/topbar/bluetooth_on.png
  icon_bt_off: /home/admin/Icons/topbar/bluetooth_off.png
  icon_bt_connected: /home/admin/Icons/topbar/bluetooth_connected.png
  show_clock: true
  clock_format: "%H:%M"
  show_notifications: true
  show_battery: true
  show_wifi: true
  show_bt: true
  show_mobile: true
  padding_left: 5
  padding_right: 5
  icon_spacing: 5
  notification_spacing: 5

# Border radius values
radius:
  button: 8
  app_button: 20
  tab: 6
  warning: 6
  modal: 6
  input: 6
  app_icon: 15
  slider: 4
  slider_knob: 6

# Page indicators
indicator:
  radius: 4
  spacing: 10

# Font configuration
font:
  name: assets/fonts/Inter/Inter_18pt-SemiBold.ttf
  size: 20

# User directories
music_dir: ~/Music
badusb_dir: ~/BadUsbScripts
game_json: ~/Games/games.json

# API keys
api:
  gemini_key: "your api key"

# UI timing
warning_duration: 2000
