# ARC Configuration File
# This configuration works on both macOS and Linux
# Paths are relative to the project root and work cross-platform

screen:
  width: 480
  height: 320
  fps: 30

tab:
  width: 100
  height: 40
  margin: 5

accent_color: [204, 99, 36]

colors:
  background: [20, 20, 20]
  background_light: [250, 250, 250]
  tab_bg: [50, 50, 50]
  tab_active: [100, 100, 100]
  button: [220, 220, 220]
  button_hover: [100, 160, 210]
  text_light: [5, 5, 5]
  text: [220, 220, 220]
  warning_bg: [200, 50, 50]
  warning_text: [255, 255, 255]
  indicator: [180, 180, 180]
  indicator_active: [255, 255, 255]
  input_bg: [255, 255, 255]
  input_border: [100, 100, 100]
  input_text: [0, 0, 0]
  input_placeholder: [150, 150, 150]
  cell_bg: [220, 220, 220]
  cell_active: [240, 240, 240]
  accent: [204, 99, 36]
  slider_bg: [80, 80, 80]
  slider_fill: [50, 150, 250]
  slider_knob: [200, 200, 200]
  slider_active_knob: [255, 255, 255]

# Icon paths (relative to project root, cross-platform)
icons:
  wifi_locked: arc/assets/icons/wifi_locked.png
  wifi_unlocked: arc/assets/icons/wifi_unlocked.png

# Built-in applications
# Use 'python -m' for Python apps to ensure proper module loading
# Terminal and file manager commands will be platform-specific at runtime
builtin_apps:
  - name: Terminal
    icon: arc/assets/icons/terminal.png
    exec: "kitty --directory=~"  # Can be overridden per-platform

  - name: AI Chatbot
    icon: arc/assets/icons/AI.png
    exec: "python -m arc.apps.chatbot.main"

  - name: Calendar
    icon: arc/assets/icons/calendar.png
    exec: "python -m arc.apps.calendar.main"

  - name: RF tools
    icon: arc/assets/icons/rf.png
    exec: "python -m arc.apps.rf_tools.main"

  - name: IR tools
    icon: arc/assets/icons/ir.png
    exec: "python -m arc.apps.ir_tools.main"

  - name: NFC tools
    icon: arc/assets/icons/nfc.png
    exec: "python -m arc.apps.nfc_tools.main"

  - name: WiFi tools
    icon: arc/assets/icons/wifi_tools.png
    exec: "python -m arc.apps.wifi_tools.main"

  - name: Bluetooth tools
    icon: arc/assets/icons/bluetooth_tools.png
    exec: "python -m arc.apps.bluetooth_tools.main"

  - name: Files
    icon: arc/assets/icons/files.png
    exec: "pcmanfm"  # Linux: pcmanfm, macOS: open ~

  - name: Text editor
    icon: arc/assets/icons/editor.png
    exec: "python -m arc.apps.notes.main"

  - name: Music
    icon: arc/assets/icons/music.png
    exec: "python -m arc.apps.music_player.main"

  - name: Games
    icon: arc/assets/icons/games.png
    exec: "python -m arc.apps.games.main"

  - name: ARC connect
    icon: arc/assets/icons/arc_connect.png
    exec: "python -m arc.apps.connect.ip"

# Directory paths (relative paths work on both platforms)
apps_dir: arc/apps
packages_dir: packages

# Grid layout
grid:
  cols: 4
  rows: 2
  margin: 10
  padding: 30
  x_offset: 4
  y_offset: 0

# Cell dimensions
cell:
  width: 90
  height: 90

# Top bar configuration
topbar:
  height: 30
  bg: [20, 20, 20]
  fg: [200, 200, 200]
  notification_dot: [245, 88, 88]
  icons: []
  icon_battery: arc/assets/icons/topbar/battery.png
  icon_mobile: arc/assets/icons/topbar/cellular.png
  wifi_icons:
    - arc/assets/icons/topbar/wifi_0.png
    - arc/assets/icons/topbar/wifi_1.png
    - arc/assets/icons/topbar/wifi_2.png
    - arc/assets/icons/topbar/wifi_3.png
    - arc/assets/icons/topbar/wifi_4.png
  icon_bt_on: arc/assets/icons/topbar/bluetooth_on.png
  icon_bt_off: arc/assets/icons/topbar/bluetooth_off.png
  icon_bt_connected: arc/assets/icons/topbar/bluetooth_connected.png
  show_clock: true
  clock_format: "%H:%M"
  show_notifications: true
  show_battery: true
  show_wifi: true
  show_bt: true
  show_mobile: true
  padding_left: 5
  padding_right: 5
  icon_spacing: 5
  notification_spacing: 5

# Border radius values
radius:
  button: 8
  app_button: 20
  tab: 6
  warning: 6
  modal: 6
  input: 6
  app_icon: 15
  slider: 4
  slider_knob: 6

# Page indicators
indicator:
  radius: 4
  spacing: 10

# Font configuration (relative path)
font:
  name: arc/assets/fonts/Inter/Inter_18pt-SemiBold.ttf
  size: 20

# User directories (~ expands on both macOS and Linux)
music_dir: ~/Music
badusb_dir: ~/BadUsbScripts
game_json: ~/Games/games.json

# API keys and secrets
api:
  gemini_key: "your api key"

# UI timing
warning_duration: 2000

# Platform-specific settings (optional overrides)
# These can be used to override settings based on the detected platform
platform:
  macos:
    terminal_cmd: "open -a Terminal"
    file_manager: "open ~"
  linux:
    terminal_cmd: "kitty --directory=~"
    file_manager: "pcmanfm"
